Fix error in migrations
I was getting the following error when running 0035:
AttributeError: 'Edition' object has no attribute 'get_rank',

But that line seems to be unnecessary, since save() does the same thing,
and we are already calling that.